name: Create release PR

on: [workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if latest commit is a merge commit
        id: check_merge
        run: |
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ $LATEST_COMMIT_MESSAGE == Merge* ]]; then
            echo "Error: Latest commit is a merge commit. Release creation is not allowed."
            exit 1
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile --yolo

      - name: Build
        run: bun run build

      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          repo-url: hiddentao/chatfall
          skip-github-release: true
