name: Publish Release

on:
  pull_request:
    types:
      - closed

permissions:
  pages: write
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-github-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile --yolo

      - name: Syncing package.json versions
        run: bun run update-versions

      - name: Build
        run: bun run build

      - name: Create GitHub Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: true
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          repo-url: hiddentao/chatfall

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./client/dist/chatfall.* ./server/dist-bin/chatfall-* ./server/dist/chatfall-server.*
          

  publish-npm:
    needs: create-github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Syncing package.json versions
        run: bun run update-versions

      - name: Build
        run: bun run build

      - name: Publish Client NPM package
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          bun run publish-npm

  publish-docs:
    needs: create-github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: cd website && bun run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
